config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users ,only: [:show,:edit , :create ,:edit , :destroy];
  resources :books ,only: [:new , :index , :show ,:create ,:edit , :destroy];
  get 'homes/about' ,  to: 'homes#about' , as: 'about'
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  
  # userが1になるので
  has_many :book, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email]) # 注目
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @books = Book.all.order(id: :asc)
    @book = Book.new
  end

  def show
    @books = Book.all.order(id: :asc)
    @book = Book.find(params[:id])
  end

  def create
    @books = Book.all.order(id: :asc)
    @book = Book.new(book_params)

    if @book.save!
      flash[:notice] = "Book was successfully created."
    end
    render :index
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title, :introduction).merge(user_id:current_user.id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @books = Book.all.order(id: :asc)
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-mod-3">
      <h2>User info</h2>
      <!--ここに判定のコードが入る (画像)-->

      <!--user情報を格納する-->
      <table class="table">
        <tr>
          <th>name</th>
          <!--ログインユーザー名-->
          <th></th>
        </tr>
        <tr>
          <th>introduction</th>
          <!--user introduction-->
          <th></th>
        </tr>
      </table>
      <!--user編集機能リンク-->
      <div class="row">
        <%= link_to 'test' ,class: 'btn btn-outline-secondary btn-block' %>
      </div>

      <!--create book要素-->
      <h2 class="mt-3">New Book</h2>
      <%= form_with model: @book ,url: '/books' , method: :post  do |f| %>

      <div class="form-group">
        <!--判定部分は削除-->
          <div class="field">
            <label>Title</label>
            <%= f.text_field :title , class: 'form-control book_title'%>
          </div>
          <div class="field">
            <label>Opinion</label>
            <%= f.text_area :introduction, class: 'form-control book_body'%>
          </div>
        </div>
        <!--送信処理-->
        <div class="action">
          <%= f.submit 'Create Book' , class: 'btn btn-success'%>
        </div>
    </div>
    <% end %>


    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <!--ここにループ文を記載-->
          <% @books.each do |book| %>
          <tr>
            <td><%= book.title %></td>
            <td><%= link_to book.introduction , book_path(book.id) %></td>
            <td><%= link_to 'Edit'  ,edit_book_path(book.id)%></td>
            <td><%= link_to 'Destroy' , book_path(book.id) , method: :delete , "data-confirm" => "Are you sure?" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      <!--iconの追加-->
      Welcome to <strong>Bookers</strong>
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <strong>Bookers</strong>!!</h1>
      <p>In<strong>Bookers,</strong></p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in' , new_user_session_path , class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to 'Sign up' , new_user_registration_path , class: 'btn btn-success btn-sm btn-block sign_up'%>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers" , '/' , class: 'navbar-brand'%>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
          <nav>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
               <ul class="navbar-nav ml-auto">
                <li>
                  <i class="fa-regular fa-house">house</i>
                 <%= link_to "Homes" , '/' ,class: 'nav-link text-light' %>
                </li>

                <% if user_signed_in? %>
                  <li>
                    <%= link_to "Users" , user_path(current_user.id)  , class: 'nav-link text-light'%>
                  </li>
                  <li>
                    <%= link_to "Books" , books_path ,class: 'nav-link text-light' %>
                  </li>
                  <li>
                    <%= link_to "Log out", destroy_user_session_path , method: :delete ,class: 'nav-link text-light'%>
                  </li>
                <% else %>
                  <li>
                    <%= link_to "About", about_path , class: 'nav-link text-light'%>
                  </li>
                  <li>
                    <%= link_to "Sign Up", new_user_registration_path , class: 'nav-link text-light' %>
                  </li>
                  <li>
                    <%= link_to "Log in", new_user_session_path , class: 'nav-link text-light'%>
                  </li>
                <% end %>
              </ul>
          </div>
      </nav>


  </header>


    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-mod-3">
      <h2>User info</h2>
      <!--ここに判定のコードが入る (画像)-->

      <!--user情報を格納する-->
      <table class="table">
        <tr>
          <th>name</th>
          <!--ログインユーザー名-->
          <th></th>
        </tr>
        <tr>
          <th>introduction</th>
          <!--user introduction-->
          <th></th>
        </tr>
      </table>
      <!--user編集機能リンク-->
      <div class="row">
        <%= link_to 'test' ,class: 'btn btn-outline-secondary btn-block' %>
      </div>

      <!--create book要素-->
      <h2 class="mt-3">New Book</h2>
      <%= form_with model: @book ,url: '/books' , method: :post do |f| %>

      <div class="form-group">
        <!--判定部分は削除-->
          <div class="field">
            <label>Title</label>
            <%= f.text_field :title, class: 'form-control book_title'%>
          </div>
          <div class="field">
            <label>Opinion</label>
            <%= f.text_area :body, class: 'form-control book_body'%>
          </div>
        </div>
        <!--送信処理-->
        <div class="action">
          <%= f.submit 'Create Book' , class: 'btn btn-success'%>
        </div>
        <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <!--ここにループ文を記載-->
        </tbody>
      </table>
    </div>

    </div>
  </div>
</div>